language: cpp

sudo: required

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -qq libboost-system-dev libboost-filesystem-dev libboost-program-options-dev
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  email: false

os:
  - linux
  - osx
